//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.20 at 09:36:46 上午 CST 
//

package cn.ac.sec.exhibition.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for area complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="area">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="device" type="{http://www.sec.ac.cn/exhibition-1.2}device"/>
 *         &lt;/choice>
 *         &lt;element name="timeline" type="{http://www.sec.ac.cn/exhibition-1.2}timeline"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "area", propOrder = { "device", "timeline" })
public class Area implements IItemFinder<Device, String> {

	protected List<Device> device;
	@XmlElement(required = true)
	protected Timeline timeline;
	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the device property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the device property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDevice().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Device }
	 * 
	 * 
	 */
	public List<Device> getDevice() {
		if (device == null) {
			device = new ArrayList<Device>();
		}
		return this.device;
	}

	/**
	 * Gets the value of the timeline property.
	 * 
	 * @return possible object is {@link Timeline }
	 * 
	 */
	public Timeline getTimeline() {
		return timeline;
	}

	/**
	 * Sets the value of the timeline property.
	 * 
	 * @param value
	 *            allowed object is {@link Timeline }
	 * 
	 */
	public void setTimeline(Timeline value) {
		this.timeline = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	@Override
	public Device getItemByKey(String key) {
		if (key == null || "".equals(key))
			return null;
		for (Device dev : this.device) {
			if (dev.getId().equals(key)) {
				return dev;
			}
		}
		return null;
	}

}
