//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.20 at 09:36:46 上午 CST 
//

package cn.ac.sec.exhibition.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the cn.ac.sec.exhibition.domain package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Exhibition_QNAME = new QName(
			"http://www.sec.ac.cn/exhibition-1.2", "exhibition");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: cn.ac.sec.exhibition.domain
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Parameter }
	 * 
	 */
	public Parameter createParameter() {
		return new Parameter();
	}

	/**
	 * Create an instance of {@link Device }
	 * 
	 */
	public Device createDevice() {
		return new Device();
	}

	/**
	 * Create an instance of {@link Timeline }
	 * 
	 */
	public Timeline createTimeline() {
		return new Timeline();
	}

	/**
	 * Create an instance of {@link Exhibition }
	 * 
	 */
	public Exhibition createExhibition() {
		return new Exhibition();
	}

	/**
	 * Create an instance of {@link Operation }
	 * 
	 */
	public Operation createOperation() {
		return new Operation();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link Area }
	 * 
	 */
	public Area createArea() {
		return new Area();
	}

	/**
	 * Create an instance of {@link Command }
	 * 
	 */
	public Command createCommand() {
		return new Command();
	}

	/**
	 * Create an instance of {@link TimePoint }
	 * 
	 */
	public TimePoint createTimePoint() {
		return new TimePoint();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Exhibition }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sec.ac.cn/exhibition-1.2", name = "exhibition")
	public JAXBElement<Exhibition> createExhibition(Exhibition value) {
		return new JAXBElement<Exhibition>(_Exhibition_QNAME, Exhibition.class,
				null, value);
	}

}
