//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.20 at 09:36:46 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sec.ac.cn/exhibition-1.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cn.ac.sec.exhibition.domain;

