//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.20 at 09:36:46 上午 CST 
//

package cn.ac.sec.exhibition.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for parameter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="parameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="BOOLEAN"/>
 *             &lt;enumeration value="INTEGER"/>
 *             &lt;enumeration value="DECIMAL"/>
 *             &lt;enumeration value="STRING"/>
 *             &lt;enumeration value="DATE"/>
 *             &lt;enumeration value="TIME"/>
 *             &lt;enumeration value="DATETIME"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameter")
public class Parameter {

	@XmlAttribute(required = true)
	protected String type;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute
	protected String minValue;
	@XmlAttribute
	protected String maxValue;

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the minValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMinValue() {
		return minValue;
	}

	/**
	 * Sets the value of the minValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMinValue(String value) {
		this.minValue = value;
	}

	/**
	 * Gets the value of the maxValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaxValue() {
		return maxValue;
	}

	/**
	 * Sets the value of the maxValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMaxValue(String value) {
		this.maxValue = value;
	}

}
